### ISSUE TITLE
Date out of range in some timestamps

### ISSUE THREAD

**Issue by mouradvt04** [rayyanqcri/rayyan-dedup#1]
```
kubectl logs deduper-69cf9b8897-r6p5r 
INFO:rayyandedup:Starting pyworker...
INFO:dedupe.api:((SimplePredicate: (firstIntegerPredicate, journal), SimplePredicate: (tokenFieldPredicate, title)), (SimplePredicate: (nearIntegersPredicate, authors), TfidfNGramCanopyPredicate: (0.2, year)), (SimplePredicate: (commonThreeTokens, journal), SimplePredicate: (firstIntegerPredicate, title)), (SimplePredicate: (commonTwoTokens, journal), SimplePredicate: (firstIntegerPredicate, title)), (SimplePredicate: (firstIntegerPredicate, title), TfidfNGramCanopyPredicate: (0.8, year)), TfidfTextCanopyPredicate: (0.6, title), SimplePredicate: (doubleMetaphone, title))
INFO:rayyandedup:Connected to database
INFO:rayyandedup:Running Job 76238565
INFO:rayyandedup:Running DedupJob.run
INFO:rayyandedup:Reading review articles
ERROR:rayyandedup:Job 76238565 raised error: Traceback (most recent call last):
  File "/home/src/pyworker/pyworker/worker.py", line 66, in run
    job.run()
  File "/home/rayyandedup/dedup_job.py", line 118, in run
    database=self.database, logger=self.logger)
  File "/home/rayyandedup/launchers.py", line 35, in launch_single_dedup
    data_d = read_review_data(review_id, with_abstracts, database, logger)
  File "/home/rayyandedup/db_helpers.py", line 53, in read_review_data
    cursor.execute(query)
DataError: date out of range for timestamp


ERROR:rayyandedup:DedupJob 72378 failed
INFO:rayyandedup:Job 76238565 finished in 0 seconds
Traceback (most recent call last):
  File "app.py", line 94, in <module>
    main()
  File "app.py", line 91, in main
    max_run_time, queue_names)
  File "/home/rayyandedup/launchers.py", line 81, in launch_worker
    worker.run()
  File "/home/src/pyworker/pyworker/worker.py", line 74, in run
    job.set_error_unlock(error_str)
  File "/home/src/pyworker/pyworker/job.py", line 102, in set_error_unlock
    self.error(error)
  File "/home/rayyandedup/dedup_job.py", line 111, in error
    self._set_status('finished', 1)
  File "/home/rayyandedup/dedup_job.py", line 25, in _set_status
    self.database.cursor().execute(query)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

```

**Comment by hammady** [comment]
That was fixed in 207ee1cc86d00acda299e33ae6d2fe0b3615f8cd.
